name: "Actual Budget"
slug: "actual_budget"
description: "Self-hosted Actual Budget server"
version: "1.0.0"
arch:
  - aarch64
  - armv7
  - amd64
startup: services
boot: auto
ports:
  5006/tcp: 5006
options: {}
schema: {}
image: "ghcr.io/actualbudget/actual-server:latest"
